:- module(
  svg_gv,
  [
    gif_to_svg_dom/3 % +GraphInterchangeFormat:compound
                     % -SvgDom:list(compound)
                     % +Options:list(nvpair)
  ]
).

/** <module> SVG: GraphViz

SVG as generated by GraphViz.

@author Wouter Beek
@see [GraphViz](http://www.graphviz.org)
@version 2014/11
*/

:- use_module(library(option)).

:- use_module(plGraphViz(gv_file)).

:- use_module(plSvg(svg_file)).



%! gif_to_svg_dom(
%!   +GraphInterchangeFormat:compound,
%!   -SvgDom:list(compound),
%!   +Options:list(nvpair)
%! ) is det.

gif_to_svg_dom(Gif, SvgDom, Options1):-
  % Make sure the file type of the output file is SvgDom.
  merge_options([to_file_type=svg], Options1, Options2),
  gif_to_gv_file(Gif, ToFile, Options2),
  file_to_svg(ToFile, SvgDom),
  delete_file(ToFile).
