:- module(
  svg_gv,
  [
    export_graph_to_svg_dom/3 % +ExportGraph:compound
                              % -SvgDom:list(compound)
                              % +Options:list(nvpair)
  ]
).

/** <module> SVG: GraphViz

SVG as generated by GraphViz.

@author Wouter Beek
@see [GraphViz](http://www.graphviz.org)
@version 2014/11
*/

:- use_module(library(option)).

:- use_module(plGraphViz(gv_file)).

:- use_module(plSvg(svg_file)).

:- predicate_options(export_graph_to_svg_dom/3, 3, [
  pass_to(export_graph_to_gv_file/3, 3)
]).





%! export_graph_to_svg_dom(
%!   +ExportGraph:compound,
%!   -SvgDom:list(compound),
%!   +Options:list(nvpair)
%! ) is det.

export_graph_to_svg_dom(ExportGraph, SvgDom, Options1):-
  % Make sure the file type of the output file is SvgDom.
  merge_options([output(svg)], Options1, Options2),
  export_graph_to_gv_file(ExportGraph, ToFile, Options2),
  file_to_svg(ToFile, SvgDom),
  delete_file(ToFile).

